# Generated by Django 3.1.2 on 2021-06-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmovies.genero')),
            ],
        ),
    ]
