# Generated by Django 3.1.2 on 2021-06-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='peliculas'),
        ),
    ]
